input_device_name: 'Logicool Mic'
output_device_name: 'Logicool Speaker'
in_rate: 16000
out_rate: 24000
frame_period: 5
buffer_time: 0.4
extract_f0_mode: world
vocoder_buffer_size: 1024
in_norm: 0.125
out_norm: 2.0
input_silent_threshold: 80
silent_threshold: -80
encode_extra_time: 0.0
convert_extra_time: 0.5
decode_extra_time: 0.0

f0_converter_input_statistics_path: './trained/f0_statistics/hiho_f0stat.npy'
f0_converter_target_statistics_path: './trained/f0_statistics/yukari_f0stat.npy'
stage1_config_path: './trained/multi-16k-ref24k-el8-woD-gbc8/config.json'
stage1_model_path: './trained/multi-16k-ref24k-el8-woD-gbc8/predictor_2910000.npz'
stage2_config_path: './trained/sr-noise3-more-gbc8/config.json'
stage2_model_path: './trained/sr-noise3-more-gbc8/predictor_400000.npz'
